ARG GOVERSION=1.24
FROM docker.io/golang:${GOVERSION}
# install helm
RUN set -xe; \
  apt-get update && apt-get install -y curl; \
  curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash


