ARG GOVERSION=1.24

FROM docker.io/golang:${GOVERSION} AS builder
ARG VERSION=master
RUN set -xe; \
  CGO_ENABLED=0 go install -v github.com/katenary/katenary/cmd/katenary@$VERSION;

FROM scratch
LABEL org.opencontainers.image.source=https://github.com/katenary/katenary
LABEL org.opencontainers.image.description="Katenary converts compose files to Helm Chart"
LABEL org.opencontainers.image.licenses=MIT
COPY --from=builder /go/bin/katenary /usr/local/bin/katenary
VOLUME /project
WORKDIR /project
ENTRYPOINT ["/usr/local/bin/katenary"]
