FROM registry.fedoraproject.org/fedora:42
RUN set -eux; \
  microdnf -y install \
  rubygems rpmbuild bsdtar mingw-nsis-base.x86_64 mingw32-nsis.noarch; \
  microdnf clean all;

# create user with 999 UID/GID
RUN set -eux; \
  groupadd -g 999 builder && \
  useradd -m -r -u 999 -g 999 -d /home/builder -s /bin/bash builder && \
  chown builder:builder /home/builder

USER builder
ENV PATH="/home/builder/bin:${PATH}"
WORKDIR /home/builder
RUN set -eux; \
  gem install fpm



